language: node_js
node_js:
- 14
cache:
  directories:
  - node_modules
script:
- npm test
env:
  global:
  - secure: OROKwacygmcaDs2yxAVBMFbcANX0VvpivBEQotXeBpBtTprzqxxG2KvhBEg1IsUoUv+BTGUYDxuzsbqjzFdTCjaHPN5K+8I7YbGvUmi5hbjGd3cRpRiBiG9YTwAMd+5ICLZUQ56jDFf9Va3hvFTo9boaZ/AkB9KQBQ51cFwKaQUubsSmcuDv60oWNfVsL9v0DaYxb5aOCXDxP3oaqNS0QZj1BxlgJ8PwTrDnuQ0m3oD/91q5GC1moLDx7p3IuUD77BsvCbfsjKzAixFv9YB6pcV0bevWZep3qPCXy7RNGNy0ctq/H+2dQUzAXUsT6I2hjAIHjM7D6rxHqGR+DlJNmNheSPp5kmX6ETYPzEHmqaAhnYTbm/Zv4sL86qkNSLGjT52JtbapOy8gJMqIB8XH26IDUyhOd+gav0lKscTtOtE5w7lk7zanwBHN1wVufq8IBa39aNb2aJ+OaocqqmF3H4fbuf92fVmiDEOZoogHFgc6kZftUVZ/Lwral6vTP5TT54CXYOM9N5Fb2d54RdJRbP35XUxfpQ7zewM2T8jMOPSkHyYl+9BAlFf92jgM9tKVCX78P7XfBAJbXuP3/XAJxXaY5HPLGLTveheUlhMUkKyq8EKhixVWIx6Mrms/OJvJiwzr9EJiIiWu+h1kBKcMngbeurlT0g3+IFYdjUQxfDU=
  - secure: WEWg+fQIflXyBI7A0iQWW0Z0rW6dIHwvXNN2qLqri/MvbdCvG7tOWrWZY5boaqbutAlTHlPr9pUXiDJVLUvevaOxzDsI/g+nrR/gBCV1aXUNaxJdgD+A9SPTu8kogSaVH7vdihSRvzS6THY28GZm3ADfTsDZN9FkqsAzAlmlBSnnwViQZVi21fGjknhJXReQn+T9mkXCqCyY8WeZL2rQU5QOeLnkTOR8XpXPvWb7dRBGqcKNIt9TsiA1ssSyIKCsRP92IsMPjZYt+HLz7TUVnpnH/PmnRr3rD0Hcxzg3k9VfcnArCEX+fJwQStOSi6mj8+o+SPLfIVkKqM/2yZiofbTKuCQZCBQqfj9lMDf1f1qhz0twfSDc+iKFbl2n13EwjAaHsJUctNABT0xoKwNp6o/kzxe8lPxTj8CApFeQV+0dy+Y/T/F7E0fMziI5nSAYvnqnO32prt8aF6ENyp0gWjYr+cI6KEnq08tMP2FW7NTh1XxbHG2SAs/4J79FAzDPlD16qmZtsMc2uXAQMGAWBvMvf6CCY3rvD6SSpDESeyQu74HlA4ujl7CmrXyo1AmohDgIxempuNILayqafmmW7RnrPhWv7gRM9o3jx8va6VzD7aq1OY9KA9a5UFYjL9+WB9TFZCyjj181yLweZ5D4e8Om834eViW8qJtvEAmieNc=
